### PR TITLE
HTTP Post/Get key retrieving

### PR DESCRIPTION
**Pull request by aetiom**
Add $inline parameter into key retrieving methods to determine if a key should be inline trimed or not (can be replaced by a type checking, but not sure it worth it because sometimes a simple text or html code can be inline too)

Add $type parameter into secureUnknownType

Add type managment into secureUnknownType as 'htlm' type need a special process

Add strip_tags() method to securise data that are not html data

Force addslashes() use instead of SqlSecureMethod call into secure methods. We don't need SqlSecureMethod, as we don't know what it does (it's part of SGBDR) and as securing http data is not part of SQL process as we do not use that data into a SQL treatment for now. SQL protect/quote should only be used with SQL treatment. It's bfw-sql (or other sql module) purpose.

### CODE REVIEW

**Comment by aetiom** [comment]
I do not merge, i let the maintainer correct conceptual errors if needed

**Comment by bulton-fr** [comment]
About force-pushed just before : @aetiom have commit some changes on this repo instead of on his fork. He ask me to remove commit from this repo, so force-push.

About travis task : 
https://blog.travis-ci.com/2013-06-10-secure-env-in-pull-requests

> which allows for the use of secure environment variables if a pull request’s target repository is the same as the source repository.

So it's normal when travis failed on `composer config -g github-oauth.github.com $GH_TOKEN`.

**Comment by bulton-fr** [comment]
Seem to be ok for me. Just missing unit test to be accepted :wink:

**Comment by bulton-fr** [comment]
Re-check
* You also need to remove the config property `sqlSecureMethod` into `/skel/app/config/bfw/global.php` ;) (think to adapt the alignment of spaces on other properties)
* The method `\BFW\Helpers\Secure::getSqlSecureMethod` can be remove.
* The method `\BFW\Helpers\Secure::secureUnknownType` now always return a string (maybe before too), so you can declare the return type.
Also, the line doing more than 80 characters, so need line-breaks (PSR-2)
```php
    public static function secureUnknownType(
        $data,
        string $type,
        bool $htmlentities
    ): string {
```
* For unit test, I will send you updated file if you want (I know you have no much time)

**Comment by aetiom** [comment]
It seems good to me.

**Comment by bulton-fr** [comment]
All green after merge https://travis-ci.org/bulton-fr/bfw/builds/484412656 :smile:

**Pull request merged**
